% -------------------------
% Normal run, reproducible
% -------------------------
opts = struct( ...
    'seed', 1, ...
    'shuffleDuringStationary', false, ...
    'shuffleMode', 'normal', ...
    'plotEvery', 10, ...
    'fileSuffix', "_normal.mat");

HD_Attractor_Model_Final([6],[9],[1],[0.262], opts);


% --------------------------------
% Head-restrained run, reproducible
% --------------------------------
opts = struct( ...
    'seed', 1, ...
    'shuffleDuringStationary', true, ...
    'shuffleFraction', 1.0, ...
    'shuffleMode', 'head_restrained', ...
    'plotEvery', 10, ...
    'fileSuffix', "_head_restrained.mat");

HD_Attractor_Model_Final([6],[9],[1],[0.262], opts);
